### ISSUE TITLE
Enhancement: UI Issues in Application

### ISSUE THREAD

**Issue by driyash9881** [Kiran-pro2001/hackathon2024IITBhuRoundGrandFinale#38]
# UI Issues in Application

#### Description:
The button in the application lacks consistency with the overall UI design. The current button design appears flat and does not align with the application's rounded UI elements.

#### Visual Reference:
![Button Design Issue](https://github.com/Kiran-pro2001/hackathon2024IITBhuRoundGrandFinale/assets/118407844/dd264f4e-af26-44c9-9294-ebfd43fde739)

#### Suggested Fix:
- Add a top margin to the button's section to provide better spacing.
- Apply rounded corners to the button to match the application's UI design.

#### Description:
The padding around the content in the section is insufficient, causing the content to appear cramped.

#### Visual Reference:
![Padding Issue](https://github.com/Kiran-pro2001/hackathon2024IITBhuRoundGrandFinale/assets/118407844/17f0ac6b-5d64-4bfe-b2d2-2e6fce2c28bb)

#### Suggested Fix:
- Increase the padding around the content to enhance readability and visual appeal.

### CSS Adjustments

1. **Button Styling**:
   - Add the following CSS to round the button and provide margin:

     ```css
     .button-class {
       border-radius: 10px; /* Adjust the radius to match the desired roundness */
       margin-top: 20px; /* Add appropriate margin */
     }
     ```

2. **Padding Adjustment**:
   - Modify the CSS to increase padding around the content:

     ```css
     .content-section {
       padding: 20px; /* Adjust padding value as needed */
     }
     ```

These changes will help the application's UI to appear more cohesive and improve overall user experience.

---

Please review the proposed solution and adjust the values according to the application's design standards.
